# https://docs.docker.com/compose/compose-file/

version: '2'

services:
  zookeeper1:
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        myid: 1
    networks:
      zk_net:
        ipv4_address: 172.19.0.3
    volumes:
      - ./zookeeper_data:/zookeeper_data
    extra_hosts:
        zookeeper1: 172.19.0.3
        zookeeper2: 172.19.0.4
        zookeeper3: 172.19.0.5
  zookeeper2:
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        myid: 2
    networks:
      zk_net:
        ipv4_address: 172.19.0.4
    extra_hosts:
        zookeeper1: 172.19.0.3
        zookeeper2: 172.19.0.4
        zookeeper3: 172.19.0.5
  zookeeper3:
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        myid: 3
    networks:
      zk_net:
        ipv4_address: 172.19.0.5
    extra_hosts:
        zookeeper1: 172.19.0.3
        zookeeper2: 172.19.0.4
        zookeeper3: 172.19.0.5
  zkstatus:
    build:
      dockerfile: Dockerfile.zkstatus
      context: .
    networks:
      - zk_net
    extra_hosts:
        zookeeper1: 172.19.0.3
        zookeeper2: 172.19.0.4
        zookeeper3: 172.19.0.5
  zkcli:
    build:
      dockerfile: Dockerfile.zkcli
      context: .
    stdin_open: true
    tty: true
    networks:
      - zk_net
    extra_hosts:
        zookeeper1: 172.19.0.3
        zookeeper2: 172.19.0.4
        zookeeper3: 172.19.0.5

networks:
  zk_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
