FROM openjdk:8-jre-alpine

ARG MIRROR=http://apache.mirrors.pair.com
ARG VERSION=3.4.9

RUN apk add --no-cache wget bash \
    && mkdir /opt \
    && wget -q -O - $MIRROR/zookeeper/zookeeper-$VERSION/zookeeper-$VERSION.tar.gz | tar -xzf - -C /opt \
    && mv /opt/zookeeper-$VERSION /opt/zookeeper \
    && mkdir -p /tmp/zookeeper

COPY zoo.cfg /opt/zookeeper/conf/zoo.cfg

WORKDIR /opt/zookeeper

ENTRYPOINT ["/opt/zookeeper/bin/zkCli.sh"]
CMD ["help"]
